version: '3.4'

networks:
  icopnet:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.97.97.0/24
#        gateway: 172.97.97.1

volumes:
  data_volume:
    external: true
    name: icop_neo4j_data_volume
  conf_volume:
    external: true
    name: icop_neo4j_conf_volume

services:

  neo4j_database:
    env_file:
    - ./.env
    build: ./
    ports:
    - 7473:7473
    - 7474:7474
    - 7687:7687
    cap_add:
    - SYS_RESOURCE
    volumes:
    - data_volume:/data
    - conf_volume:/conf
    - ./data:/data
    - ./conf:/conf
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    networks:
      icopnet:
        ipv4_address: 172.97.97.2